### ISSUE TITLE
Clan Rank Change

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wjlafrance/jinxbot#19]
```
What steps will reproduce the problem?
1. Change a users rank.
2.
3.

What is the expected output? What do you see instead?
It errors out when a clan rank is changed.

Please use labels and text to provide additional information.
System.Collections.Generic.KeyNotFoundException was unhandled
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowKeyNotFoundException()
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at BNSharp.BattleNet.BattleNetClient.HandleClanRankChange(ParseData pd)
       at BNSharp.BattleNet.BattleNetClient.Parse()
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:
```

Original issue reported on code.google.com by `MiKeOwNaGe@gmail.com` on 29 Jun 2009 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
This issue will not be accepted unless you can submit a packet log.
```

Original comment by `myndf...@valhallalegends.com` on 10 Jul 2009 at 8:33
- Added labels: **Component-Logic**, **Type-Defect**, **Usability**

**Comment by GoogleCodeExporter** [comment]
Original comment by `myndf...@valhallalegends.com` on 10 Jul 2009 at 8:34
- Added labels: **Issue-NeedsPacketLog**

**Comment by GoogleCodeExporter** [comment]
```
packetlog

0000   ff 7a 09 00 19 6d 0d e3 08                       .z...m...

I know it's returning 0x08 because i attempted to set a user the same rank he 
was,
but even if i have it change a user rank i get the error also.
```

Original comment by `MiKeOwNaGe@gmail.com` on 13 Jul 2009 at 6:43

**Comment by GoogleCodeExporter** [comment]
```
never mind the issue was i was sending the packet on my own rather then through 
BN#.
```

Original comment by `MiKeOwNaGe@gmail.com` on 25 Jul 2009 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
Closed because the user was not using the BN# API to do the change.
```

Original comment by `myndf...@valhallalegends.com` on 31 Jul 2009 at 7:03
- Changed state: **Invalid**
