### ISSUE TITLE
ArgumentException 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wjlafrance/jinxbot#22]
```
After running 5 bots online doing relatively consistent work (sending a
chat message every ~5 seconds) for over 36 hours, this exception was thrown:

System.ArgumentException was unhandled
  Message=Source array was not long enough. Check srcIndex and length, and
the array's lower bounds.
  Source=mscorlib
  ParamName=""
  StackTrace:
       at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array
destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
       at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
       at System.Collections.Generic.Queue`1.Enqueue(T item)
       at
BNSharp.BattleNet.BattleNetClient.__InvokeInformationReceived(Priority p,
ServerChatEventArgs e)
       at BNSharp.BattleNet.BattleNetClient.InvokeHelper`1.Invoke(Priority p)
       at BNSharp.BattleNet.BattleNetClient.__MedPriorityEventWatcher()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
ignoreSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 


In the Arguments object:
m_txt = "*LeaF(Hero@Azeroth"
m_flags = 0x00000000.
```

Original issue reported on code.google.com by `richardpianka` on 15 Jan 2010 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
This looks like an issue with synchronization.  The exception came from within 
the .NET Framework library (the Queue<T>.Enqueue method).
```

Original comment by `myndf...@valhallalegends.com` on 16 Jan 2010 at 7:02
- Changed state: **Accepted**
- Added labels: **Component-Logic**, **Priority-High**, **Type-Defect**
